# Generated by Django 4.2.7 on 2023-11-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0028_friendship_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.TextField(default='https://mincute2205.pythonanywhere.com/', max_length=255),
        ),
    ]
