# Generated by Django 4.2.7 on 2023-11-30 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0031_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='liked',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_Groupposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
