# Generated by Django 4.2.7 on 2023-11-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0032_grouppost_liked_grouppost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='images',
            field=models.ManyToManyField(blank=True, to='app_social.image'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='video',
            field=models.ManyToManyField(blank=True, to='app_social.video'),
        ),
    ]
